apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nautobot-node-labeler.fullname" . }}
  labels:
    {{- include "nautobot-node-labeler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nautobot-node-labeler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nautobot-node-labeler.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "nautobot-node-labeler.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NAUTOBOT_URL
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.nautobotConfig.existingSecret }}{{ .Values.nautobotConfig.existingSecret }}{{ else }}{{ include "nautobot-node-labeler.fullname" . }}-credentials{{ end }}
                  key: {{ .Values.nautobotConfig.existingUrlKey | default "url" }}
            - name: NAUTOBOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.nautobotConfig.existingSecret }}{{ .Values.nautobotConfig.existingSecret }}{{ else }}{{ include "nautobot-node-labeler.fullname" . }}-credentials{{ end }}
                  key: {{ .Values.nautobotConfig.existingSecretKey | default "token" }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 