apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nautobot-node-labeler.fullname" . }}-credentials
  labels:
    {{- include "nautobot-node-labeler.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.nautobotConfig.token }}
  token: {{ .Values.nautobotConfig.token | b64enc }}
  {{- end }}
  {{- if .Values.nautobotConfig.url }}
  url: {{ .Values.nautobotConfig.url | b64enc }}
  {{- end }} 